baseURL = 'https://maxdevnix.github.io/hugo-web'
languageCode = 'en-us'
title = "MaxDev's Blog"
theme = "ananke"
summaryLength = "10"
[pagination]
  disableAliases = true
  pagerSize = 10
  path = 'page'
  paginate = 10

[outputs]
home = ["HTML", "AMP", "RSS", "JSON"]

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
codeFences = true
guessSyntax = true
hl_Lines = ""
lineNoStart = 1
lineNos = false
lineNumbersInTable = false
tabWidth = 8
noClasses = false

[params]
defaultTheme = "dark"
search = true
author = "MaxDevNix"
description = "Blog about fixing various errors I encountered throughout my journey with Linux."

[params.contact]
email = "maxik.falb@gmail.com"

[build]
[build.buildStats]
disableClasses = false
disableIDs = false
disableTags = false
enable = false

[caches]
  [caches.images]
    dir = ':cacheDir/images'
